### ISSUE TITLE
autoreconf-2.71 fails due to duplicate AM_INIT_AUTOMAKE in configure.ac

### ISSUE THREAD

**Issue by berndf** [openSUSE/catatonit#20]
On gentoo I have autoreconf-2.71 by default with which reconfiguring fails - Removing the second AM_INIT_AUTOMAKE at the end of configure.ac suffices to fix it.

Log:
autoreconf-2.71: export WARNINGS=
autoreconf-2.71: Entering directory '.'
autoreconf-2.71: configure.ac: not using Gettext
autoreconf-2.71: running: aclocal --force 
configure.ac:34: error: AM_INIT_AUTOMAKE expanded multiple times
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:19: the top level
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:34: the top level
autom4te-2.71: error: /usr/bin/m4 failed with exit status: 1
aclocal-1.16: error: /usr/bin/autom4te-2.71 failed with exit status: 1
autoreconf-2.71: error: aclocal failed with exit status: 1

**Comment by yann-morin-1998** [comment]
Isn't that fixed by 99bb9048f532257f3a2c3856cfa19fe957ab6cec?

**Comment by berndf** [comment]
> Isn't that fixed by [99bb904](https://github.com/openSUSE/catatonit/commit/99bb9048f532257f3a2c3856cfa19fe957ab6cec)?

Thanks - yes, confirmed!

**Comment by benjamb** [comment]
@cyphar Could we get a new release with this fix?

**Comment by cyphar** [comment]
0.2.0 has been released. Sorry for the wait.
