### ISSUE TITLE
configure fails to generate Makefile

### ISSUE THREAD

**Issue by stefins** [openSUSE/catatonit#22]
Hi,
Running on 20.04.1-Ubuntu x86_64 GNU/Linux
`sudo ./configure`

returns

```shell
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 2812: syntax error near unexpected token `2.4.2'
./configure: line 2812: `LT_PREREQ(2.4.2)'
```

thanks

**Comment by tobwen** [comment]
You need to install `libtool` and re-run `./autogen.sh`.

**Comment by cyphar** [comment]
Yes, you need to install `libtool`. Also I would recommend against running `sudo ./configure`. You don't need root privileges to generate the `Makefile` and a bug in automake/autoconf could cause you serious issues.
