### ISSUE TITLE
Is there a special reason for GPLv3+?

### ISSUE THREAD

**Issue by afreof** [openSUSE/catatonit#23]
Is there is a special reason for the GPLv3 license? Or could re-licensing this project e.g. under GPLv2+ be considered?

The problem with GPLv3 is that users are not allowed to integrate Catatonit into products whose owner does not have the possibility to recompile Catatonit himself and replace it on the device. For example, in the case of a car, this results in a conflict of objectives: How can you certify the vehicle with software in such a way that you are allowed to drive it on the road, if you have to assume that the owner himself can change something in the software?

Since Linux containers are also becoming more and more important in the area of embedded devices, I think Catatonit would be even more valuable if users were also allowed to integrate it into products.

Actually a change of the license would perhaps still be possible. It would require the approval of all authors.

**Comment by gsalvatella** [comment]
I agree with the comments from @afreof. `catatonit` is an important dependency for e.g. podman, which will increasingly be used in embedded systems.

**Comment by cyphar** [comment]
I completely forgot about this issue... Let me open a PR for a vote. By my count, the only people who need to approve this change are:

```
Aleksa Sarai <cyphar@cyphar.com>
Andrey Golovizin <ag@sologoc.com>
Giuseppe Scrivano <gscrivan@redhat.com>
Miquel Sabaté Solà <msabate@suse.com>
Thibault Nélis <tnelis@stammed.net>
Valentin Rothberg <vrothberg@suse.com>
```

And the patches by Andrey Golovizin and Thibault Nélis are small enough (one-line in both cases) that we could revert them in the absolute worst case.

**Comment by afreof** [comment]
Thank you very much.

**Comment by giuseppe** [comment]
for trivial contributions, it shouldn't even matter since they are not significant for copyright purposes, e.g. even GNU projects accept such contributions without copyright papers: https://www.gnu.org/prep/maintain/maintain.html#Legally-Significant

**Comment by cyphar** [comment]
Yeah, I'm aware of the GNU guidelines on legally significant contributions and they're probably right, but I'd prefer to get everyone's approval so we can avoid any legal questions entirely.

**Comment by afreof** [comment]
@cyphar Would it help if we open a pull request? Which license would be the preferred one?

**Comment by cyphar** [comment]
I was trying to decide between GPLv2+ and MPL-2.0. If you're okay with GPLv2+ we can just stick with that?

**Comment by afreof** [comment]
GPLv2+ is perfect.

**Comment by gsalvatella** [comment]
Thank you for the effort guys! This makes podman much more usable now.
