### ISSUE TITLE
Catatonit Version String: Is this a bug?

### ISSUE THREAD

**Issue by jradxl** [openSUSE/catatonit#29]
Please can someone explain the version string:-

```
$ catatonit --version
tini version 0.2.0_catatonit
```

It looks like some sort of bug, string error!

Can't we have something more conventional like:-

```
$ conmon --version
conmon version 2.1.10
commit: 09bcded8e9c49cf1ff1fda403feac5a08f22535f-dirty
```

I can then parse it better in my script using lastversion

**Comment by cyphar** [comment]
No, it's intentional. Docker assumes the binary name is "tiny" so in order to be a drop-in replacement we need to fake the name of the program. Otherwise `docker info` won't output any version information.

**Comment by jradxl** [comment]
OK, thanks for info. I'm using Podman so I didn't know.
I'll parse out the version number from the string.
You can close this
